version: '{build}'
image:
  - Visual Studio 2015
  - Ubuntu
configuration:
  - Debug
  - Release
build_script:
  - ps: echo "Building for $env:CONFIGURATION"
  - ps: dotnet build
test_script:
  - ps: dotnet test ./test/DotnetConf2018Demo.Tests/DotnetConf2018Demo.Tests.csproj /p:CollectCoverage=true
